name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: gh-metrics/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Options
          user: jordanxion
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/New_York
          plugin_achievements: yes
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 60
          plugin_languages_recent_load: 1000
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_lines: yes
